config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  root "static_pages#home"
  get "/help", to: "static_pages#help", as: "herf"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/user.rb
class User < ApplicationRecord
  before_save {Email.downcase!}
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :Email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence:true, length: {minimum: 6}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = "")
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the"%> <%= link_to t(".tuto"),"https://www.railstutorial.org/"%>
    <%=t ".by"%> <%= link_to "Micheal Hart"%>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t ".news" %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), herf_path %></li>
        <li><%= link_to t(".login"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%=stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload"%>
    <%=javascript_include_tag "application", "data-turbolinks-track": "reload"%>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, t(".about") %>
<h1><%= t ".about" %></h1>
<p>
  <%= t ".the"%> <%= link_to t(".tuto"),"https://www.railstutorial.org/"%>
  <%= t ".is"%> <%= link_to t(".book"),"https://www.railstutorial.org/book"%>
  <%= t ".and"%>
  <%= link_to t(".screencasts"),"http://screencasts.railstutorial.org/"%>
  <%= t ".toteach"%> <%= link_to t(".ruby"),"http://rubyonrails.org/"%>
  <%= t ".end"%>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".contact") %>
<h1><%= t ".contact" %></h1>
<p>
  <%= t ".info" %>
  <%= link_to t(".contact page"), "https://www.railstutorial.org/contact"%>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".help") %>
<h1><%= t ".help" %></h1>
<p>
  <%= t ".gethelp"%> <%= link_to t("Rails Tutorial help section"),
  "https://www.railstutorial.org/help"%>
  <%= t ".toget"%> <%= link_to t("Ruby on Rails Tutorial book"),
  "https://www.railstutorial.org/book"%>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t ".welcome"%></h1>

  <h2>
    <%= t ".info"%> <%= link_to t(".tuto"), "https://www.railstutorial.org/" %>
    <%= t ".end"%>
  </h2>
  <%= link_to t(".signup"), signup_path , class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
  "http://rubyonrails.org/" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>